'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';
const inter = Inter({ subsets: ["latin"] });
import { CartProvider } from "@/app/context/CardContext"; // Ensure this is the correct path



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
      <body className={inter.className}>
        
        {children}
      </body>
      </CartProvider>

    </html>
  );
}
